openapi: 3.0.3
info:
  title: NJFProjects API
  description: This is the API documentation for the NJFProjects API.
  version: 1.0.0
tags:
  - name: Accounts
    description: Accounts and Sessions related operations
  - name: Profiles
    description: Profiles related operations
  - name: Tags
    description: Tags and Tag Categories related operations
  - name: Projects
    description: Projects and Files related operations
servers:
  - url: https://example.com
paths:
  /accounts/{id}:
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      tags:
      - Accounts
      summary: View Account
      operationId: viewAccountWithId
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
    put:
      tags:
      - Accounts
      summary: Modify Account
      operationId: modifyAccountWithId
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Account'
    delete:
      tags:
      - Accounts
      summary: Delete Account
      operationId: deleteAccountWithId
      responses:
        '204':
          description: No Content
components:
  securitySchemes:
    MyToken:
      type: apiKey
      in: header
      name: Authorization
  schemas:
    Account:
      type: object
      properties:
        id:
          type: string
          readOnly: true 
        email:
          type: string
          format: email
        created_time:
          type: string
          format: date-time 
          writeOnly: true  
        password:
          type: string
          format: password 
          writeOnly: true 
          minLength: 8
    Profile:
      type: object
      properties:
        id:
          type: string
          readOnly: true 
        name:
          type: string
          minLength: 2 
          maxLength: 50
        description:
          type: string
        updated_time:
          type: string
          format: date-time 
          writeOnly: true
        profile_photo:
          type: string
    Tag:
      type: object
      properties:
        id:
          type: string
          readOnly: true 
        tag_category_id:
          type: string
          readOnly: true
        name:
          type: string
          minLength: 2 
          maxLength: 50
    Tag Category:
      type: object
      properties:
        id:
          type: string
          readOnly: true
        name:
          type: string
          minLength: 2 
          maxLength: 50
        color:
          type: string
    File:
      type: object
      properties:
        id:
          type: string
          readOnly: true
        project_id:
          type: string
          readOnly: true
        name:
          type: string
          minLength: 2 
          maxLength: 50
        reference:
          type: string
        uploaded_time:
          type: string
          format: date-time 
          writeOnly: true
    Project:
      type: object
      properties:
        id:
          type: string
          readOnly: true
        account_id:
          type: string
          readOnly: true
        share:
          type: string
          enum:
            - public
            - private
        name:
          type: string
          minLength: 2 
          maxLength: 50
        like_number:
          type: integer
          minLength: 0
        watch_number:
          type: integer
          minLength: 0
        bookmark_number:
          type: integer
          minLength: 0
        from_date:
          type: string
          format: date
        to_date:
          type: string
          format: date
        team_size:
          type: integer
          minLength: 0
        summary:
          type: string
        created_time:
          type: string
          format: date-time 
          writeOnly: true
        photo:
          type: string
    Session:
      type: object
      properties:
        user_id:
          type: string
        auth_header:
          type: string
    Error: 
      type: object
      properties:
        title:
          type: string
          description: Error title